DROP DATABASE IF EXISTS Bot;
CREATE DATABASE Bot DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE Bot;

DROP USER 'ircBot'@'localhost';
CREATE USER 'ircBot'@'localhost' IDENTIFIED BY 'morn';

CREATE TABLE Type(
Type_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Type_ID),
Name VARCHAR(30)
) ENGINE = INNODB;

CREATE TABLE User(
User_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(User_ID),
Nick VARCHAR(50) NOT NULL,
UNIQUE(Nick),
Password VARCHAR(32) NOT NULL,
WhoIs TEXT
) ENGINE = INNODB;

CREATE TABLE Tag(
Tag_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Tag_ID),
Name VARCHAR(50) NOT NULL,
UNIQUE(Name)
) ENGINE = INNODB;

CREATE TABLE Log(
Log_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Log_ID),
Command TEXT NOT NULL,
User INT NOT NULL,
FOREIGN KEY(User) REFERENCES User(User_ID),
Time Timestamp NOT NULL DEFAULT NOW()
) ENGINE = INNODB;

CREATE TABLE Link(
Link_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Link_ID),
Link TEXT NOT NULL,
LinkHash VARCHAR(32) NOT NULL,
UNIQUE(LinkHash),
TimeAdded TIMESTAMP NOT NULL DEFAULT NOW(),
Type INT NOT NULL,
FOREIGN KEY(Type) REFERENCES Type(Type_ID),
User INT,
FOREIGN KEY(User) REFERENCES User(User_ID)
) ENGINE = INNODB;

CREATE TABLE LinkTag(
Tag_ID INT NOT NULL,
Link_ID INT NOT NULL,
FOREIGN KEY(Tag_ID) REFERENCES Tag(Tag_ID),
FOREIGN KEY(Link_ID) REFERENCES Link(Link_ID),
PRIMARY KEY(Tag_ID,Link_ID)
) ENGINE = INNODB;

CREATE TABLE UserNickHistory(
UserNick_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(UserNick_ID),
Nick VARCHAR(50) NOT NULL,
UNIQUE(Nick),
User INT NOT NULL,
FOREIGN KEY(User) REFERENCES User(User_ID),
TimeChanged TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE = INNODB;

CREATE TABLE Room(
Room_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Room_ID),
ServerName TEXT NOT NULL,
RoomName TEXT NOT NULL,
Hash VARCHAR(32),
UNIQUE(Hash)
) ENGINE = INNODB;

CREATE TABLE RoomTopicHistory(
Topic_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Topic_ID),
Topic TEXT,
Room_ID INT NOT NULL,
FOREIGN KEY(Room_ID) REFERENCES Room(Room_ID)
) ENGINE = INNODB;

CREATE TABLE Reminder(
Reminder_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Reminder_ID),
Reminder TEXT NOT NULL,
User INT NOT NULL,
FOREIGN KEY(User) REFERENCES User(User_ID),
Time TIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE Email(
Email_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Email_ID),
Email TEXT
) ENGINE = INNODB;

CREATE TABLE TelePhonenumber(
Number_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Number_ID),
Number TEXT
) ENGINE = INNODB;

CREATE TABLE RSSFeed(
Feed_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Feed_ID),
Feed TEXT NOT NULL,
FeedHash VARCHAR(32) NOT NULL,
UNIQUE(FeedHash)
) ENGINE = INNODB;

CREATE TABLE UserFeed(
User_ID INT NOT NULL,
FOREIGN KEY(User_ID) REFERENCES User(User_ID),
Feed_ID INT NOT NULL,
FOREIGN KEY(Feed_ID) REFERENCES RSSFeed(Feed_ID),
PRIMARY KEY(User_ID, Feed_ID)
) ENGINE = INNODB;

CREATE TABLE Todo(
Todo_ID INT NOT NULL,
PRIMARY KEY(Todo_ID),
Todo TEXT
) ENGINE = INNODB;

CREATE TABLE Trademark(
TM_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(TM_ID),
Trademark TEXT NOT NULL,
TM_Hash VARCHAR(32) NOT NULL,
UNIQUE(TM_Hash),
User TEXT NOT NULL
#FOREIGN KEY(User) REFERENCES User(User_ID),
) ENGINE = INNODB;

#DROP TABLE Command;
CREATE TABLE Command(
Command_ID INT AUTO_INCREMENT,
PRIMARY KEY(Command_ID),
Command VARCHAR(32) NOT NULL,
UNIQUE(Command),
Short_Description TEXT NOT NULL,
Long_Description TEXT NOT NULL
) ENGINE = INNODB;

#ALTER TABLE Unit ADD Faction VARCHAR(10);
CREATE TABLE Unit(
Unit_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Unit_ID),
Unit_Name VARCHAR(32),
Faction VARCHAR(10)
) ENGINE = INNODB;

#DROP TABLE Quotes;
CREATE TABLE Quotes(
Quote_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Quote_ID),
Quote VARCHAR(50),
Unit_ID INT NOT NULL,
FOREIGN KEY(Unit_ID) REFERENCES Unit(Unit_ID)
) ENGINE = INNODB;

GRANT ALL ON Bot.* TO 'ircBot'@'localhost';