//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.18 at 02:48:48 PM CEST 
//


package botMk2.APIs.fanartTV;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fanartTV package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fanartTV
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fanart }
     * 
     */
    public Fanart createFanart() {
        return new Fanart();
    }

    /**
     * Create an instance of {@link Fanart.Movie }
     * 
     */
    public Fanart.Movie createFanartMovie() {
        return new Fanart.Movie();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviebanners }
     * 
     */
    public Fanart.Movie.Moviebanners createFanartMovieMoviebanners() {
        return new Fanart.Movie.Moviebanners();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviebackgrounds }
     * 
     */
    public Fanart.Movie.Moviebackgrounds createFanartMovieMoviebackgrounds() {
        return new Fanart.Movie.Moviebackgrounds();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviethumbs }
     * 
     */
    public Fanart.Movie.Moviethumbs createFanartMovieMoviethumbs() {
        return new Fanart.Movie.Moviethumbs();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviediscs }
     * 
     */
    public Fanart.Movie.Moviediscs createFanartMovieMoviediscs() {
        return new Fanart.Movie.Moviediscs();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviearts }
     * 
     */
    public Fanart.Movie.Moviearts createFanartMovieMoviearts() {
        return new Fanart.Movie.Moviearts();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Movielogos }
     * 
     */
    public Fanart.Movie.Movielogos createFanartMovieMovielogos() {
        return new Fanart.Movie.Movielogos();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Movieposters }
     * 
     */
    public Fanart.Movie.Movieposters createFanartMovieMovieposters() {
        return new Fanart.Movie.Movieposters();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Hdmovielogos }
     * 
     */
    public Fanart.Movie.Hdmovielogos createFanartMovieHdmovielogos() {
        return new Fanart.Movie.Hdmovielogos();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Hdmoviecleararts }
     * 
     */
    public Fanart.Movie.Hdmoviecleararts createFanartMovieHdmoviecleararts() {
        return new Fanart.Movie.Hdmoviecleararts();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviebanners.Moviebanner }
     * 
     */
    public Fanart.Movie.Moviebanners.Moviebanner createFanartMovieMoviebannersMoviebanner() {
        return new Fanart.Movie.Moviebanners.Moviebanner();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviebackgrounds.Moviebackground }
     * 
     */
    public Fanart.Movie.Moviebackgrounds.Moviebackground createFanartMovieMoviebackgroundsMoviebackground() {
        return new Fanart.Movie.Moviebackgrounds.Moviebackground();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviethumbs.Moviethumb }
     * 
     */
    public Fanart.Movie.Moviethumbs.Moviethumb createFanartMovieMoviethumbsMoviethumb() {
        return new Fanart.Movie.Moviethumbs.Moviethumb();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviediscs.Moviedisc }
     * 
     */
    public Fanart.Movie.Moviediscs.Moviedisc createFanartMovieMoviediscsMoviedisc() {
        return new Fanart.Movie.Moviediscs.Moviedisc();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Moviearts.Movieart }
     * 
     */
    public Fanart.Movie.Moviearts.Movieart createFanartMovieMovieartsMovieart() {
        return new Fanart.Movie.Moviearts.Movieart();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Movielogos.Movielogo }
     * 
     */
    public Fanart.Movie.Movielogos.Movielogo createFanartMovieMovielogosMovielogo() {
        return new Fanart.Movie.Movielogos.Movielogo();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Movieposters.Movieposter }
     * 
     */
    public Fanart.Movie.Movieposters.Movieposter createFanartMovieMoviepostersMovieposter() {
        return new Fanart.Movie.Movieposters.Movieposter();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Hdmovielogos.Hdmovielogo }
     * 
     */
    public Fanart.Movie.Hdmovielogos.Hdmovielogo createFanartMovieHdmovielogosHdmovielogo() {
        return new Fanart.Movie.Hdmovielogos.Hdmovielogo();
    }

    /**
     * Create an instance of {@link Fanart.Movie.Hdmoviecleararts.Hdmovieclearart }
     * 
     */
    public Fanart.Movie.Hdmoviecleararts.Hdmovieclearart createFanartMovieHdmovieclearartsHdmovieclearart() {
        return new Fanart.Movie.Hdmoviecleararts.Hdmovieclearart();
    }

}
